import React from 'react';
import type { Metadata } from 'next';
import { inter, lexendDeca } from '@/app/fonts';
import { cn } from '@/lib/utils';
import './globals.css';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
      <body className={cn(inter.variable, lexendDeca.variable, 'font-inter')}>
      {children}
      </body>
      </html>
    </SessionProvider>
  );
}
